name: Node.js CI

on:
  push:
    branches: [main, feature/*, ci/*]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        run: npm ci && npm run build

      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run coverage

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: nodev${{matrix.node-version}}
          path: test-output/*.xml

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        if: matrix.node-version == '17.x'
        with:
          files: ./coverage/cobertura-coverage.xml

  publish-rest-results:
    runs-on: ubuntu-latest
    needs: build-test
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: testresults

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: testresults/**/*.xml
